{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Functions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "On this lab we will put to practice some of the concepts we have learned on this past few days.\n",
    "\n",
    "`NOTE: On this lab you should try to write all the functions yourself using only the most basic of python syntax and without functions such as len, count, sum, max, min, in, etc. Give it a try. 🧑🏻‍💻👩🏻‍💻`\n",
    "\n",
    "The cell after each exercise contains a few tests to check if your function works as expected."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mod.testing import *\n",
    "import unittest"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Write a function that returns the greater of two numbers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "def greater(a,b):\n",
    "    if a > b:\n",
    "        return a\n",
    "    else:\n",
    "        return b"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 161,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.375s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greater(greater)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Now write a function that returns the largest element on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 162,
   "metadata": {},
   "outputs": [],
   "source": [
    "def greatest(arr):\n",
    "    max_ = arr[0]\n",
    "    for number in arr: \n",
    "        if number > max_:\n",
    "            max_ = number\n",
    "    return max_"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 163,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.459s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greatest(greatest)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Write a function that sums all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 164,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sum_all(arr):\n",
    "    total = 0\n",
    "    for number in arr:\n",
    "        total = total + number\n",
    "    return total"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 165,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.400s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_sum(sum_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Write another function that multiplies all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 166,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mult_all(arr):\n",
    "    total = 1\n",
    "    for number in arr:\n",
    "        total = total * number\n",
    "    return total"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 167,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.348s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mult(mult_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Now combine those two ideas and write a function that receives a list and either \"+\" or \"*\" and outputs acordingly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 234,
   "metadata": {},
   "outputs": [],
   "source": [
    "def oper_all(arr, oper):\n",
    "    if oper == \"+\":\n",
    "        return sum(arr)\n",
    "    elif oper == \"*\":\n",
    "        total = 1\n",
    "        for number in arr:\n",
    "            total = total * number\n",
    "        return total\n",
    "  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 235,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FF.....FF....FF..F.FF..FF.F.F..FFFFFF.F..FFF..FF.F.FF...F..FFF.FF.FF.FFF.....FFF..F...FFFF.F.......F\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 602112000 : Should be 602112000\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 1023958410854400 : Should be 1023958410854400\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 15485161835338886283264000000000000 : Should be 15485161835338886283264000000000000\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 24390120480768000 : Should be 24390120480768000\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 668482906464715218862945075200000000000000 : Should be 668482906464715218862945075200000000000000\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 18662400 : Should be 18662400\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -4354560 : Should be -4354560\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != -6019743744000 : Should be -6019743744000\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 0 : Should be 0\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_operations.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 78, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: None != 4719287416484232010137600000 : Should be 4719287416484232010137600000\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.169s\n",
      "\n",
      "FAILED (failures=49)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_operations(oper_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Write a function that returns the factorial of a number."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 170,
   "metadata": {},
   "outputs": [],
   "source": [
    "def factorial(n):\n",
    "    product = 1\n",
    "    for i in range(1, n + 1):\n",
    "        product = product * i\n",
    "    return product\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.419s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_factorial(factorial)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Write a function that takes a list and returns a list of the unique values.\n",
    "\n",
    "`NOTE: You cannot use set. 🤔`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 171,
   "metadata": {},
   "outputs": [],
   "source": [
    "def unique(arr):\n",
    "    uniques = []\n",
    "    for number in arr:\n",
    "        if number not in uniques:\n",
    "            uniques.append(number)\n",
    "    return uniques"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 172,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.650s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_unique(unique)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Write a function that returns the mode of a list, i.e.: the element that appears the most times.\n",
    "`NOTE: You should not use count... 🧐`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mode_counter(arr):\n",
    "    return mode(arr)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.392s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mode(mode_counter)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Write a function that calculates the standard deviation of a list.\n",
    "`NOTE: Do not use any libraries or already built functions. 😉`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 236,
   "metadata": {},
   "outputs": [],
   "source": [
    "def st_dev(arr):\n",
    "    average = sum(arr)/len(arr)\n",
    "    sumatorio = 0\n",
    "    for number in arr: \n",
    "        sumatorio = sumatorio + (number - average)**2\n",
    "    std = (sumatorio/(len(arr)-1))\n",
    "    return std**(1/2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 237,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "...EE..E.....EE...EE...EEE.E.....EEE....EE.....E.....E.E...EEE..E.E..E.E...E.....EE..E..E....E.E..E.\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5,msg=f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.163s\n",
      "\n",
      "FAILED (errors=34)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_stdev(st_dev)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Write a function to check if a string is a pangram, i.e.: if it contains all the letters of the alphabet at least once."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 187,
   "metadata": {},
   "outputs": [],
   "source": [
    "def pangram(string):\n",
    "    string.split(\",\")\n",
    "    alphabet = [\"a\", \"b\", \"c\", \"d\" ,\"e\" ,\"f\", \"g\", \"h\", \"i\" ,\"j\", \"k\", \"l\", \"m\", \"n\",\"ñ\", \"o\", \"p\", \"q\", \"r\", \"s\", \"t\", \"u\", \"v\", \"w\", \"x\", \"y\", \"z\"]\n",
    "    for i in alphabet:\n",
    "        if i not in string:\n",
    "            return False\n",
    "        else:\n",
    "            return True\n",
    "            "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 188,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "................EEE.EEEEEE.E..\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pangram.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 172, in runTest\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 30 tests in 0.140s\n",
      "\n",
      "FAILED (errors=10)\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# This will test your function \n",
    "test_pangram(pangram)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 11. Write a function that receives a string of comma separated words and returns a string of comma separated words sorted alphabetically.\n",
    "\n",
    "`NOTE: You may use sorted but not split and definitely no join! 🤪`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "#def sort_alpha(string):\n",
    "#    sorted_list = (sorted(list(string)))\n",
    "#    return str(sorted_list)\n",
    "#No entiendo porque no sale aqui.\n",
    "\n",
    "def sort_alpha(string):\n",
    "    lista_2 = []\n",
    "    for w in string:\n",
    "        lista_2.append(w)\n",
    "    return sorted(lista_2)\n",
    "        \n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [884 chars] 'z'] != 'asbm,chvq,ctajvpiyq,dwxrfx,ehggarfxwc,ez[142 chars]zwgk' : Should be asbm,chvq,ctajvpiyq,dwxrfx,ehggarfxwc,ezstveh,futgfaxd,fzlufxw,gdgsw,grgintf,ipwo,jpwyvbvlio,kufza,nblfibh,ntkz,nvbljws,obtdefywm,qzasxxeda,uugjkhoeeb,yfggwqhs,zonoafbubq,zqamjodycl,zwgk\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [864 chars] 'z'] != 'bmixj,bvgtfn,bvmuzrljny,csgs,eqnyws,gyyg[138 chars]fopr' : Should be bmixj,bvgtfn,bvmuzrljny,csgs,eqnyws,gyygonlkyf,hxcgqv,ilgjjkj,iqehlw,jzhbfvgudp,kxcl,mnilncgph,moidkvfwzm,opbgzjsne,pmrcoujw,qjafrm,riotaxsgm,skgeehjjjf,uvvxm,xjjsoi,xjqulywa,zxdfopr\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [854 chars] 'z'] != 'barumm,dhechjlkra,eolbtbhuv,hbsoxxcop,hl[136 chars]ylbn' : Should be barumm,dhechjlkra,eolbtbhuv,hbsoxxcop,hlndnoacbx,jyqxykdz,lxgzbq,muojhkn,ncse,nniqdnp,ntoh,ovdqpwhpn,phkci,pxwypr,pzfkntq,qmpljgi,snsnfgt,tijt,vdexixr,vfxcvzc,wdyzunif,ycsvnpx,ylbn\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [289 chars] 'z'] != 'beiil,jfvm,kjdw,kyju,ngmhr,siedqffe,vetz[23 chars]gmzn' : Should be beiil,jfvm,kjdw,kyju,ngmhr,siedqffe,vetzvjsdd,vxldqtnnrt,wzqcksgmzn\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [564 chars] 'z'] != 'bcpsja,bmagnky,cwdaaihmfe,dbldntebb,dtsd[78 chars]fumc' : Should be bcpsja,bmagnky,cwdaaihmfe,dbldntebb,dtsdh,dzfv,fekx,ganclidp,gobjhjgtj,ivsnfg,mlkidmwa,qofiwmwjj,rlfbrefeg,sixtfbab,xofumc\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [564 chars] 'z'] != 'ekhccvy,jebvzzmxqv,mgjfpecgpj,owntybjjhn[78 chars]tgre' : Should be ekhccvy,jebvzzmxqv,mgjfpecgpj,owntybjjhn,qenujxwuvl,rsmvezcnqi,tahb,ugzkmzfn,vlghskeyz,xgemmjott,xwkbtdgfq,ywisrzb,zfvtgre\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [484 chars] 'z'] != 'aqvhdoeou,dmfarawefo,hyos,iywbtwffl,jsan[62 chars]whgp' : Should be aqvhdoeou,dmfarawefo,hyos,iywbtwffl,jsantitivj,lbokq,ozslgqq,plvn,sqnyiz,tjwd,tyiutoouzc,xtvqiqhpa,yitwhgp\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [984 chars] 'z'] != 'bicg,bilgld,bqhidgtaka,disbewb,efkrc,eoy[162 chars]uiej' : Should be bicg,bilgld,bqhidgtaka,disbewb,efkrc,eoyj,fxaldsd,gqseqvyhv,ixexsuevpc,khlffpdwst,lgkmvdrwf,mfqnzkfqzm,mufqgsevd,nxxnbel,ovrovfcmpf,rerxa,sltnz,srez,vwgtktlc,wdtcbhhho,wgbexqzgu,xbyqkkft,xuiocsliuz,zzqeuiej\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', 'a', [254 chars] 'z'] != 'ckcq,ekefik,hwwqiib,rdsyk,saipndcld,sspm[16 chars]ivqh' : Should be ckcq,ekefik,hwwqiib,rdsyk,saipndcld,sspmbp,vzwjtqibuo,xlivqh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [524 chars] 'z'] != 'hpzfshw,ibeszwl,jzki,kgkyabld,mieuz,mxwh[70 chars]ygmt' : Should be hpzfshw,ibeszwl,jzki,kgkyabld,mieuz,mxwhdyu,oohm,oraz,qvcqacknal,rmrzze,rtgyqq,tans,tdjiijb,twdpu,tymh,xxgy,ymygmt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [334 chars] 'z'] != 'dsbcsjkx,igqooivsbu,jgeugk,nhyd,pignes,s[32 chars]mcdu' : Should be dsbcsjkx,igqooivsbu,jgeugk,nhyd,pignes,skguroid,taycrat,zjvzlfldly,zqhzimcdu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [594 chars] 'z'] != 'imdckecsye,iofgps,ixksqnua,kofi,ntenlevn[84 chars]pttr' : Should be imdckecsye,iofgps,ixksqnua,kofi,ntenlevnlw,nwnwutv,ojmzwcujlh,oxftn,ozusktxd,qnkrztxna,ralaplmtvj,smrfrl,swgr,tjmx,vxpev,vxrpttr\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [964 chars] 'z'] != 'aigygsavhf,bojtvtkgk,buijpypc,bvipaeujn,[158 chars]kztz' : Should be aigygsavhf,bojtvtkgk,buijpypc,bvipaeujn,dhhdwrpv,dynfis,frzrf,fthki,gaaptizkq,guvw,htjlizbwd,koulb,kqqgdpogep,lihomonl,olwtulcwj,pixkrkh,pxejjzm,sdps,sudazz,tgymnwrbl,xcktewq,ycliyce,yczo,yfdpfai,ykkztz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [669 chars] 'z'] != 'agvlo,ajtchfz,awdglrvdr,bwibghgp,frfvitb[99 chars]vkzd' : Should be agvlo,ajtchfz,awdglrvdr,bwibghgp,frfvitb,jcwmmyi,jdhnqsub,jlpsn,jvomnkicmt,luciimup,myvg,osjaaztb,ozrli,pkulb,qyxtnd,rwzmg,slulci,ufrg,zulzvkzd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', 'a', 'a', [259 chars] 'z'] != 'dkhfrtvs,irywpf,nceundzaj,qagbvmkb,sbqfm[17 chars]nnzr' : Should be dkhfrtvs,irywpf,nceundzaj,qagbvmkb,sbqfmh,sxiottbait,vrhpnnzr\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [864 chars] 'z'] != 'bqffspv,hndnlgvrmt,jfkgafyz,kgpdpwa,lnve[138 chars]evyd' : Should be bqffspv,hndnlgvrmt,jfkgafyz,kgpdpwa,lnve,mcofcbmip,nphxvqtjx,oaiy,ofdurv,ptckcna,pzvolhak,qqzuu,skqbezefu,tpylhf,tuggxf,urht,wczxrrvxwr,xcbbsha,xdpb,xfvdg,xtnyr,yjuq,yvqaihw,zvtcevyd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', 'a', [269 chars] 'z'] != 'evodwsfo,hngfyrnoh,ktqnem,nqna,pvbints,s[19 chars]wrqc' : Should be evodwsfo,hngfyrnoh,ktqnem,nqna,pvbints,shyusurdzg,udvkjzza,wrqc\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [474 chars] 'y'] != 'ahvtar,bdbnofbj,doyc,hsmahgb,karbitwbg,k[60 chars]vohf' : Should be ahvtar,bdbnofbj,doyc,hsmahgb,karbitwbg,kwte,lhsq,maismrsp,nvuvgyuutq,ourps,pplyafo,qwomhppmc,tvbpjv,vohf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [439 chars] 'z'] != 'ckeic,glrfwarz,hzjeg,iony,ldtjmudw,pswaa[53 chars]zmyz' : Should be ckeic,glrfwarz,hzjeg,iony,ldtjmudw,pswaaiqhxl,ptihfnntru,sqmvryca,uioct,wcjvfswgwk,zlcjhxixa,zmyz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [229 chars] 'z'] != 'fkwwe,fstyex,gprjpu,jndyzvkn,jptb,rmmne,tgwf,zcrg,zctiu' : Should be fkwwe,fstyex,gprjpu,jndyzvkn,jptb,rmmne,tgwf,zcrg,zctiu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [414 chars] 'z'] != 'arxtowfs,fhegz,heqwotpbi,hmlm,ilrin,lffp[48 chars]blwe' : Should be arxtowfs,fhegz,heqwotpbi,hmlm,ilrin,lffpvmihxt,pigrb,rsxn,rxgmdxf,sggpsbek,yehtlrqm,zkarblwe\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [424 chars] 'z'] != 'gabomramo,mlzaunfup,oeuxd,qgfoao,qhlbp,q[50 chars]zvlz' : Should be gabomramo,mlzaunfup,oeuxd,qgfoao,qhlbp,qylgjxzhdc,rjjpyg,rlbmfhbmwr,vtrb,vwnepc,wdepvhnik,zvlz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [829 chars] 'z'] != 'egybndx,eutxodfcdm,fowjpqtrxc,hwtylxe,lp[131 chars]knzq' : Should be egybndx,eutxodfcdm,fowjpqtrxc,hwtylxe,lpphcn,mfafgopb,npqernbsnl,oppheisqc,qhtskzsp,qluqsbp,sijptrrf,tdgvmf,toybkyo,uaazdjbpy,uoshsfwj,xcppue,xeehmt,xlgvfwinsp,ytkjaw,zlatknzq\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [669 chars] 'z'] != 'daddppe,eghyj,flzflzze,ftdgi,gsyfrgzk,id[99 chars]tjdv' : Should be daddppe,eghyj,flzflzze,ftdgi,gsyfrgzk,idyj,jfqcx,jvvdagwvh,kxfahoegar,lglohu,monef,mybpdawawg,oarstnot,oujkdom,psvhnuwacl,vvod,wbknuz,xbldotjdv\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [624 chars] 'z'] != 'aakpjxuib,afmnpwh,bignyero,bimt,hisejndb[90 chars]oueb' : Should be aakpjxuib,afmnpwh,bignyero,bimt,hisejndbv,ildaicugk,isqjaq,ldoljizl,lkcwz,lqssanckw,omxyhlq,rgakzim,tmrwyxt,zozcijwa,zucoiemdcg,zzoueb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [364 chars] 'z'] != 'ajtsqk,bvlqdupj,kzjegzgqkh,lkmngljl,lnrb[38 chars]nzge' : Should be ajtsqk,bvlqdupj,kzjegzgqkh,lkmngljl,lnrblriikv,lwspugqcv,owogd,vpvt,xxhyy,yskqnzge\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', 'a', 'a', 'b', 'c', 'c', [119 chars] 'z'] != 'pyvrhumcw,qufhzkqfa,racrb,xsrmkcz' : Should be pyvrhumcw,qufhzkqfa,racrb,xsrmkcz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', 'a', 'a', 'a', 'a', [149 chars] 'z'] != 'mpbz,mtwfiawft,pbwtyoba,vualbpfbi,yptar' : Should be mpbz,mtwfiawft,pbwtyoba,vualbpfbi,yptar\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [394 chars] 'z'] != 'acqkn,cghhk,dhdg,fdun,fzve,hpwaoucz,iwzj[44 chars]lhlv' : Should be acqkn,cghhk,dhdg,fdun,fzve,hpwaoucz,iwzjbm,nnglopz,redvzl,ridkfe,uayzccpuop,xgwq,zymlhlv\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [389 chars] 'z'] != 'beyir,bifwqiejv,dslsjhls,eogei,nawobykx,[43 chars]vrza' : Should be beyir,bifwqiejv,dslsjhls,eogei,nawobykx,ngwggvb,oijtxbxum,olxhwz,sciptdnmjw,tfvqde,vrza\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [619 chars] 'z'] != 'adouexp,aqxvl,baag,bqvl,cbydksmp,dbqlcaq[89 chars]bfzp' : Should be adouexp,aqxvl,baag,bqvl,cbydksmp,dbqlcaqt,eurret,fbwnhg,ivlwuo,jcmtznitz,mqtd,nblhn,pbipgszlfu,rustrd,sdsdgu,vqoawr,yowgappmh,yyabfzp\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [324 chars] 'z'] != 'aghsoyifwj,cvmfr,cxazbaxnda,dlfxghloz,ij[30 chars]ysjw' : Should be aghsoyifwj,cvmfr,cxazbaxnda,dlfxghloz,ijxnpp,juzcc,nrqenjq,txautkaxeo,ysjw\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', 'a', [249 chars] 'z'] != 'azwqsyr,fsmta,glgnouti,jsobl,oscjikhfd,p[15 chars]pkbs' : Should be azwqsyr,fsmta,glgnouti,jsobl,oscjikhfd,psqhenffp,sjwi,wpkbs\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', 'a', 'b', 'b', 'b', [134 chars] 'z'] != 'bqcivqbrt,mltn,nnpbilquy,otzy,ygneak' : Should be bqcivqbrt,mltn,nnpbilquy,otzy,ygneak\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [839 chars] 'z'] != 'abobivjlf,akofpihb,bwlj,cajwtu,dgpvehdo,[133 chars]zyuy' : Should be abobivjlf,akofpihb,bwlj,cajwtu,dgpvehdo,ehnbc,hhue,hqxyzizdz,izkwe,mozb,mvemcoubqw,njssoqcru,oxqgdxoo,pwwct,qjsetrr,rppdvcr,rzoxqpm,seyuk,tfagdhpw,ufhh,ujbk,whigss,zknixtjh,zyuy\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [979 chars] 'z'] != 'apeverx,fplggdlyj,fpwagwisz,gankild,jget[161 chars]zowz' : Should be apeverx,fplggdlyj,fpwagwisz,gankild,jgetvnxbv,lbflnkuxg,lfqlaumnks,nnxpwo,npaxlraacb,ofeqhyjk,qrgj,roubixxfl,ruxtjfp,rvwsfmtuhv,rwhkbn,rynvxiuo,smmwwwm,sqsclx,swodtx,uqcla,wugolpotsj,xzonkfrxcw,ylwvfi,zowz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [684 chars] 'z'] != 'aaxrcvdmx,bgigbdsl,czxsfjjwtw,ddqh,dski,[102 chars]meym' : Should be aaxrcvdmx,bgigbdsl,czxsfjjwtw,ddqh,dski,gwjtdew,jrvdv,mhpw,nfop,pboi,qlhgwbvs,qzeuz,sczpnqlhu,svqxzpqn,tygxfe,yjrzxoyavm,ymgtwku,ytheeliuvd,zqmeym\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', 'a', 'a', 'a', [234 chars] 'z'] != 'disjzzea,kflors,qedrtgsmx,tfwshhbdr,tmaksnqnzz,txagnouyr' : Should be disjzzea,kflors,qedrtgsmx,tfwshhbdr,tmaksnqnzz,txagnouyr\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [334 chars] 'z'] != 'bllczb,ggboixahn,jrubawv,mayxxrkfw,muwgi[32 chars]dlna' : Should be bllczb,ggboixahn,jrubawv,mayxxrkfw,muwgiawyz,nbih,pvvluf,utdhmlefx,zvkbndlna\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [384 chars] 'z'] != 'aywco,fbhblpzjdw,fjtrtcmuv,menngukdn,pbw[42 chars]zpyd' : Should be aywco,fbhblpzjdw,fjtrtcmuv,menngukdn,pbwxtmyn,qhicrpdua,qpqpucy,qrmx,satlpunq,zfvfzpyd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [389 chars] 'x'] != 'cewkvmbu,hwcpx,ilhjhhifw,nemahteq,oskpax[43 chars]xtxt' : Should be cewkvmbu,hwcpx,ilhjhhifw,nemahteq,oskpaxsma,pjpumupd,qbibxfjnp,shwhlwhge,tksppnqv,uxtxt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [779 chars] 'z'] != 'agux,btwyeasabs,eprmyc,fkahmf,fniwwdxlks[121 chars]rhzj' : Should be agux,btwyeasabs,eprmyc,fkahmf,fniwwdxlks,gtdynhbti,jrfg,kxbta,mciqunycu,ojevigisj,piuf,plurao,rkut,swdnjk,tqcmj,ttcor,uiixhz,vpamumj,vqfudh,vyqkzdrjv,ywbaaklh,zzrhzj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', 'c', 'c', 'd', 'e', [149 chars] 'x'] != 'euvjpcohn,iulxx,kxgigs,lpvdghcwii,svfwl' : Should be euvjpcohn,iulxx,kxgigs,lpvdghcwii,svfwl\n",
      "\n",
      "======================================================================\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [394 chars] 'z'] != 'egweu,idnmqcp,izezx,julemmwet,kmooi,lzzw[44 chars]vzpl' : Should be egweu,idnmqcp,izezx,julemmwet,kmooi,lzzwvg,nbjd,ohsfpu,rirypgb,ulvfrszqpb,vawygx,vcuvzpl\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [434 chars] 'z'] != 'cxhbytcg,huormij,irjcdbmeer,jfpxdfmj,kgl[52 chars]oluy' : Should be cxhbytcg,huormij,irjcdbmeer,jfpxdfmj,kglgb,lwgiivmqit,mwqfypreu,ntlzkhm,psnc,rnpcyle,zfwi,zjoluy\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', 'a', 'a', [244 chars] 'z'] != 'agwobcdys,gmktci,khpkgji,kpucvlgkvd,shnz[14 chars]craj' : Should be agwobcdys,gmktci,khpkgji,kpucvlgkvd,shnz,uwmgbntyeh,yicraj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [334 chars] 'z'] != 'azdvbhgsk,fcdl,gyysaeziuc,jojyph,konii,l[32 chars]ywfu' : Should be azdvbhgsk,fcdl,gyysaeziuc,jojyph,konii,lgrxi,lwzrxxajh,odlkfxygqb,pzcdq,ywfu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [849 chars] 'z'] != 'abqazyk,bdaacu,bnetmqskq,chiosu,ddxjty,d[135 chars]xkrg' : Should be abqazyk,bdaacu,bnetmqskq,chiosu,ddxjty,djprzyo,dpatgsqcg,dpjokzecc,eddgrzj,eftrs,fclwwm,fmbbcq,gsyml,kwjdf,lnhb,lpwxeivzg,mhxbovduna,mitdm,ofakm,ujrhjd,wfxa,wqthnbgn,xfsrjgsk,xkrg\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [829 chars] 'z'] != 'bmvo,cfwmcnnyv,ckhitjedlu,cxwnj,dayxzd,d[131 chars]yvrz' : Should be bmvo,cfwmcnnyv,ckhitjedlu,cxwnj,dayxzd,dilxnrqu,grfr,ikfyjdoc,jckn,jjrgkrdc,jnlhyi,kqgvjkvfv,kwebbpi,loemjla,lqfkwynd,myvwstcgmj,nedfuejt,taurxkm,uetw,unbekeibzo,wyemjohs,yvrz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [669 chars] 'z'] != 'beereh,cbng,cnnwmzp,cvnnef,dhza,dobzwrdg[99 chars]ttpa' : Should be beereh,cbng,cnnwmzp,cvnnef,dhza,dobzwrdgh,fdgl,gzjcefg,jpysurmjx,mlhfoyvqmq,oclhsukgam,otloztgwpc,pqvz,sdyw,soqmenkpb,tkgq,utudts,vhtpm,ztuttpa\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [749 chars] 'z'] != 'aeec,atctejcr,dxkhectbx,gbjzrkmfy,gxcyfc[115 chars]yics' : Should be aeec,atctejcr,dxkhectbx,gbjzrkmfy,gxcyfcyyu,jfhdjqlts,jzhebzfl,lpgzgzsbhp,ohepq,ojgbfvhvz,onatz,ooxbkf,pduudsapn,uextdcds,vtaehkyh,ymixrriglh,ysypz,zgwhx,zyics\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [844 chars] 'z'] != 'agtzsgrarj,bbpbsa,dbrit,drxni,efdunzsr,f[134 chars]jpcl' : Should be agtzsgrarj,bbpbsa,dbrit,drxni,efdunzsr,feyftgbh,gwjfk,idetghosse,jdihpcmp,jjfamqsk,lldvlh,neopsqvndf,nogn,sdyjhl,sfddenz,sftm,sroy,sylndy,tpxyrsyigm,unxm,wsuvs,xpdqbct,yietbdjpcl\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', 'b', 'b', 'c', [144 chars] 'z'] != 'cfmb,dwdpwny,judcsb,pjil,vhsxk,vyddvwz' : Should be cfmb,dwdpwny,judcsb,pjil,vhsxk,vyddvwz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [594 chars] 'z'] != 'bazxstxy,encbykplaf,fhddmvd,fkiihxwvx,ge[84 chars]tpzx' : Should be bazxstxy,encbykplaf,fhddmvd,fkiihxwvx,geamjuef,ghyagnuf,gvvqbbshvc,hjog,kkgonmjra,ktbysfj,pwbrhs,qcyfgeywz,qkxdqbm,rypdhxp,stpzx\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [999 chars] 'z'] != 'bsspjbirhf,dwvsvwlwvr,eejcvfhps,ejbchlne[165 chars]grwh' : Should be bsspjbirhf,dwvsvwlwvr,eejcvfhps,ejbchlnewo,fomhdtxy,gmbhtdk,gvyqftkx,hzocpglfvr,iemiv,imdffcif,jqsfivp,lmhb,maovk,obqqfcf,ogmurw,qlbiaddkc,rjlwbzvaty,sieywi,tmkblebz,uxxkzsyb,vzpychwjzc,wybbws,yxypbshixl,zgrwh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [719 chars] 'z'] != 'agfqa,awlrvhqu,bapt,cnkqlm,cyqlrglbkl,ep[109 chars]tiqz' : Should be agfqa,awlrvhqu,bapt,cnkqlm,cyqlrglbkl,epwck,ewuqmjinl,fmmeqoep,gcpbu,jcmjapzajc,jlqueln,lizyqa,mmnc,ovrpekdpro,qcklkgwuyy,qsfkyerfs,tpbwiv,vijzfpk,zltiqz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [419 chars] 'z'] != 'hcraxo,hjrbn,jwgau,leidrfnubh,lycd,pipir[49 chars]awsh' : Should be hcraxo,hjrbn,jwgau,leidrfnubh,lycd,pipirkqbyh,tiibqqfwry,upbqlerm,urxprvzu,uyrglc,xlpwo,yawsh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [639 chars] 'z'] != 'bekyscdzn,bpssvtjd,cgeazhskex,dygjpoxfi,[93 chars]ydti' : Should be bekyscdzn,bpssvtjd,cgeazhskex,dygjpoxfi,efpjcelnj,fpsgk,hpwzfh,krgaog,mhvwunnzt,ptqmqhhm,rhtzawnuvn,saflcrqz,sflkqvqbq,vnokuzhynm,xzeydti\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', 'b', 'b', 'b', 'e', [129 chars] 'y'] != 'fblnjnbw,lubsnoquj,nrkvx,pgip,yupej' : Should be fblnjnbw,lubsnoquj,nrkvx,pgip,yupej\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [584 chars] 'z'] != 'cmbngvp,dhignd,dldiigfypu,gyikke,hblilli[82 chars]kmcf' : Should be cmbngvp,dhignd,dldiigfypu,gyikke,hblillig,iahrls,iwgxqqrq,jriiecs,msdh,ppzqb,rdbejsob,rougm,rwnjrj,twxewavgul,yejmvsebw,yokmcf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [569 chars] 'z'] != 'biwgeoa,ehgafc,fcjxpjk,izhksh,jibbnk,jrl[79 chars]wuas' : Should be biwgeoa,ehgafc,fcjxpjk,izhksh,jibbnk,jrlcn,lpfgyve,oixvut,oxyli,vaxbmors,vlswzhr,whitv,wqedwzxyv,wsbbcn,xtujwssiuu,xvmowuas\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [774 chars] 'z'] != 'aeuydqaou,chpixebs,edmwdugdj,efumrkn,eqa[120 chars]duoy' : Should be aeuydqaou,chpixebs,edmwdugdj,efumrkn,eqalcwyw,hvlk,izwsyaoul,jvlirp,nvnbazdvtc,oinetbefml,qhvlwbdf,qoifop,rfcodblpm,thbogdonqu,tmhvzbv,tyfvu,vemdx,wnpsghr,zemkjduoy\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [639 chars] 'z'] != 'dpesg,eyrmx,fcmvwmggd,gywikkodor,jlobypk[93 chars]vcsd' : Should be dpesg,eyrmx,fcmvwmggd,gywikkodor,jlobypksc,juzqyap,lllnlqqyca,lmxbq,qenuhvc,qrgkznq,rnws,siyomduz,wmzv,xgtll,yoflaokpw,yqyrwiks,zxeotvcsd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [449 chars] 'z'] != 'ckmvverhl,cxyc,dcacua,ezzzmyws,hamvicg,h[55 chars]rhvs' : Should be ckmvverhl,cxyc,dcacua,ezzzmyws,hamvicg,hvextj,jovcpopf,klnbs,kpvoinbfk,kxqjnadqu,qjtngckf,renuzrhvs\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [984 chars] 'z'] != 'aowrqkmhwi,bhzrfqi,ejucaxlqmb,fatsi,fmfg[162 chars]wfws' : Should be aowrqkmhwi,bhzrfqi,ejucaxlqmb,fatsi,fmfgmzhywq,gwwrmqsh,hcwetvt,herfbgh,iuetlxvzsd,jdfrosgfq,jxiiyyqwl,kaxzixixnc,krav,llqjvwulzh,ngfjykmmuh,oapjnrqf,odjfjgd,oxgtyqq,qwosdfs,seyy,tigg,vohhkj,xukzbxu,ybcwfws\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [509 chars] 'z'] != 'dgugqyzb,dkadgjhzcc,dkwcos,dygge,ooro,pn[67 chars]yqem' : Should be dgugqyzb,dkadgjhzcc,dkwcos,dygge,ooro,pnszvthwq,ppodhb,qwjary,relg,tvkkcr,tyeghw,wycpxwerq,ybfse,zjuycn,zjzyqem\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [424 chars] 'z'] != 'elmodjarxd,epth,fewlvdo,ibsfkaxz,jhmuhv,[50 chars]jbnz' : Should be elmodjarxd,epth,fewlvdo,ibsfkaxz,jhmuhv,jycvlwv,midejck,nbxnm,nrzbtqb,phzkgbucbo,riocjhr,wjbnz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [324 chars] 'z'] != 'bznhx,dohbviq,gcncznefhh,isfmoacck,kkjjt[30 chars]ubfu' : Should be bznhx,dohbviq,gcncznefhh,isfmoacck,kkjjtkpx,nlbyeeh,qtsu,sqierf,sxjka,ubfu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [659 chars] 'z'] != 'amly,bgtntvol,ixvvahkp,jkbfkpsuv,lsqqeuo[97 chars]zplx' : Should be amly,bgtntvol,ixvvahkp,jkbfkpsuv,lsqqeuo,mtblcr,obpmt,omndnp,qubyhhd,rssuworiq,rwdtjzxbiq,uwbcnmsq,vrhj,wnvgw,wvtlfasik,xbhayagxtt,yiel,yzplx\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', 'a', [304 chars] 'z'] != 'abtmqtccnu,jrtjymh,jyzkfnpmmu,nklkks,ohr[26 chars]xxbv' : Should be abtmqtccnu,jrtjymh,jyzkfnpmmu,nklkks,ohrpmbkk,pteptaif,uevanxactl,xxbv\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [794 chars] 'z'] != 'akdxtxidrv,bjtnjar,cupz,dmwt,gbvqssby,iz[124 chars]yliu' : Should be akdxtxidrv,bjtnjar,cupz,dmwt,gbvqssby,izbt,nwhwgdz,oimcqsm,phwbdvs,qlmgacjzub,rkpr,staxytpsc,sxiuygux,teeikuysfk,tihca,vafulynfa,vuzmp,xbacgys,xpvkicq,zlkvxfg,zrxcpyliu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [739 chars] 'z'] != 'eehr,efmdw,eybrglk,hehdcr,hmrzlkh,hsahqz[113 chars]mtqu' : Should be eehr,efmdw,eybrglk,hehdcr,hmrzlkh,hsahqztcw,iefnetgg,irjnanqz,izfxdnrpu,jtfpnryz,lgnjmlm,lhyh,mgjotee,oocsjd,oxmdbegufh,rqwype,rxjs,typdwbjz,viweqkzhaq,zmtqu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [449 chars] 'z'] != 'chccvfu,dssqahowwj,esrdbhiti,gire,htetko[55 chars]tlcu' : Should be chccvfu,dssqahowwj,esrdbhiti,gire,htetkorzfw,jqgyenhrzr,jytqmp,nvlygbodb,rdyqgjtoc,uovrnkuy,zxstlcu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [859 chars] 'z'] != 'ayhdilvoxl,azjguu,cntdann,dittgwra,dphpc[137 chars]xlxi' : Should be ayhdilvoxl,azjguu,cntdann,dittgwra,dphpchjxld,fahug,gogtp,ichhnq,iopjzyvl,irkpoiodrg,jsvsuvmbn,krarwzmcr,kywggypxbv,npgy,onlmshcbeb,siqyfp,slftokrrq,viwe,wcnwlavp,wlfy,wlsvftjq,xlxi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [504 chars] 'z'] != 'ilwfypptma,inpwo,jhfnjokd,jhlbl,kghgxd,k[66 chars]fcuo' : Should be ilwfypptma,inpwo,jhfnjokd,jhlbl,kghgxd,ktpfonq,mdelb,mspf,nalfvoo,pmpgkw,rtcipm,uzxd,wbrfm,yniljgqucs,zyxrfcuo\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [389 chars] 'z'] != 'drsvklq,fxxnriwq,jlsk,jzdczljuo,kihpwyjc[43 chars]tlar' : Should be drsvklq,fxxnriwq,jlsk,jzdczljuo,kihpwyjcew,maknufahsj,obemeelhro,pmug,pvomwtv,tfgx,tlar\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [404 chars] 'z'] != 'bfdjyr,ekmyiva,fkucsie,ggmnp,iabkmiay,ib[46 chars]yixx' : Should be bfdjyr,ekmyiva,fkucsie,ggmnp,iabkmiay,ibmqyronx,lnpkhm,nswhhs,pptvzot,zmxtcemqj,zmxxjjyixx\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [799 chars] 'z'] != 'apethddn,dmjjql,dokia,hcpuxnvx,jslqmt,lc[125 chars]byzj' : Should be apethddn,dmjjql,dokia,hcpuxnvx,jslqmt,lcvp,lfzpcmf,lxxsolaxg,mcmvoqymhy,mrbbisxlv,mxcekjqb,nkwfyntgyi,oebb,plvo,rclvirvv,uekfgzx,yfgnkqs,yieqgywfm,ymfcpy,ynez,zanzvbbyzj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [574 chars] 'z'] != 'aqega,bzmuqpgm,cfwpplulei,ddbm,fdceyvqsx[80 chars]oejl' : Should be aqega,bzmuqpgm,cfwpplulei,ddbm,fdceyvqsxz,gvpknfay,imxws,mybytu,nmtfgdjgs,rrgf,tyfbmnx,wpnhoslu,wsptrhxdgu,wvmxxag,yjaykoejl\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [679 chars] 'z'] != 'bcazkye,bsxw,djjxlhtio,enbnncg,irqzus,jo[101 chars]zxyx' : Should be bcazkye,bsxw,djjxlhtio,enbnncg,irqzus,jorzrg,kxfvh,mvkhvurk,niesgwlq,opoahycab,phnmbarct,qhhvavzgm,sigkgiyt,udqnpfad,vhpueuv,waer,zphse,zveqgzxyx\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [584 chars] 'z'] != 'drhxvlowie,fvvmtfr,hjtwckhks,hnqgpz,iopn[82 chars]ykle' : Should be drhxvlowie,fvvmtfr,hjtwckhks,hnqgpz,iopn,kxnobn,lploywkbu,mdwlr,pehrvtdvqx,qkyii,qpswhbzmns,ufcwz,ukromjetva,vpoqbt,vwfqziykle\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', 'a', 'a', 'a', [229 chars] 'z'] != 'gsteono,hhpyfuapi,hjpvvygqhd,lqmxrapb,otbspau,ykzxnobhf' : Should be gsteono,hhpyfuapi,hjpvvygqhd,lqmxrapb,otbspau,ykzxnobhf\n",
      "\n",
      "======================================================================\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', 'a', 'a', 'b', [169 chars] 'y'] != 'agkwmyh,bmbatfy,cegtnirdh,ketvi,myxibg,qcwl' : Should be agkwmyh,bmbatfy,cegtnirdh,ketvi,myxibg,qcwl\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [719 chars] 'y'] != 'agvp,bjirwtqmdw,cdnsxufl,cdxhocfepi,cyyw[109 chars]jwbc' : Should be agvp,bjirwtqmdw,cdnsxufl,cdxhocfepi,cyywh,esoibp,gyqxr,inenxmfd,jqxd,klab,lpldtddob,mwttblyuv,nwfccdqid,rjhmsw,tatrftva,urwrbs,xngrlywbt,xrmlrvcsg,yyjwbc\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [624 chars] 'z'] != 'bulflw,dzfzscuvfg,emydyqf,haddz,khkic,kk[90 chars]buty' : Should be bulflw,dzfzscuvfg,emydyqf,haddz,khkic,kkgn,kptinqihwg,nozbxjx,nxcqedjoya,tgygqydnyi,tijndpt,tivbdgg,tqgffhy,vnpju,wtrwg,zcbi,znragbuty\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [714 chars] 'z'] != 'bzieuzovg,djirgusuq,fzvsork,gnemcktwtx,h[108 chars]lxzb' : Should be bzieuzovg,djirgusuq,fzvsork,gnemcktwtx,hpzvnroou,idvguzeh,ikqdtwclum,jqbe,jzpffezq,nbcrxql,nwugr,ozmeo,pahzl,qjypzgvhi,tjhdfdae,tpwmyo,vfwzhohvh,xwflxzb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [1019 chars] 'z'] != 'aqjncymora,bnqod,bzwmpwroh,ggtgf,ghcdqbu[169 chars]dsqp' : Should be aqjncymora,bnqod,bzwmpwroh,ggtgf,ghcdqbu,glthbpgzxn,glzxaynmh,gsnvfdwnbh,iqwurrrsd,majivwsi,mgqcoyqf,mpbw,mrshql,ncvsmbabyj,nczioucx,nooskhag,pmyvjr,prsmr,qunfv,qyhrdh,wycckn,xjenllyqdo,xyncbonmnw,zeedvdrfk,zgdsqp\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [769 chars] 'z'] != 'agmls,auktlqdqze,bixyypjkoe,bqfzijchj,dn[119 chars]ugji' : Should be agmls,auktlqdqze,bixyypjkoe,bqfzijchj,dnmuckwlt,dyomz,fdbg,hawz,hlibg,ifjdik,irwmtsvyp,ldixieexc,rhrgnasnvc,slesjo,sylla,uablrvdipe,vyrhv,xhsk,zaooighkw,zxvinxugji\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [934 chars] 'z'] != 'affj,amtitsuv,anghtop,axzekkzkhu,bckrmox[152 chars]asgk' : Should be affj,amtitsuv,anghtop,axzekkzkhu,bckrmoxar,dejreqtlj,fbkikrfvdv,igjxxa,ipbc,izyjyjtj,kyufhmdnr,mwscilr,nintnvwood,qdxksrolp,szjcr,ulekzanonx,uylilxr,vfxwbsno,vnkhqmzg,wkjbhe,yhhavafu,yntm,zqovasgk\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [504 chars] 'z'] != 'bvoiytoszv,hfpjl,iafpdm,ibzhcq,ikvb,mowd[66 chars]qkal' : Should be bvoiytoszv,hfpjl,iafpdm,ibzhcq,ikvb,mowdlwuyxo,nmyoydsacn,ocjul,rqufuk,rytdm,swuffmz,volyoz,vxauvdcjn,xfbuqkal\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', 'a', 'b', 'b', [239 chars] 'y'] != 'dnheguby,hwsmdwn,napttffcj,pixbvlugo,swy[13 chars]xbtf' : Should be dnheguby,hwsmdwn,napttffcj,pixbvlugo,swypcmuuf,uufbjmxbtf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [384 chars] 'z'] != 'awmbrkzd,boizjfg,cypjt,flrvpcex,oqjeajch[42 chars]ilum' : Should be awmbrkzd,boizjfg,cypjt,flrvpcex,oqjeajchxl,xdtau,ykrmqijgve,yqetbegm,zimjneur,zpybilum\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', 'a', [249 chars] 'z'] != 'akaz,clivfluahi,cnlp,dfxcr,ewgrbtma,swtb[15 chars]fshw' : Should be akaz,clivfluahi,cnlp,dfxcr,ewgrbtma,swtb,wpwuzjqf,wwnbdfshw\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [279 chars] 'y'] != 'cnthkohfkb,gljvxc,gnic,kbwgvkdyq,lfnx,nf[21 chars]rrrc' : Should be cnthkohfkb,gljvxc,gnic,kbwgvkdyq,lfnx,nfxju,pckacrt,qvopybtf,rrrc\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [394 chars] 'z'] != 'bzdgpdwxr,ciapkpa,dhzo,dzwncfvepw,euuxsk[44 chars]xwfi' : Should be bzdgpdwxr,ciapkpa,dhzo,dzwncfvepw,euuxskmuru,jowbyvcad,relmc,stpjzhnhn,wfhztmr,wjzv,xwfi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [414 chars] 'z'] != 'edfkqw,ejlv,hqxr,jtyfwgpti,kshxjnyxb,lhc[48 chars]zzif' : Should be edfkqw,ejlv,hqxr,jtyfwgpti,kshxjnyxb,lhcayttvuv,oplujwi,szfwcmie,vtsrui,xisui,zvhlrvfkh,zzif\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [359 chars] 'z'] != 'bswh,dyqfblcq,ekwo,eyltua,hfwgo,mzrjis,q[37 chars]xjzi' : Should be bswh,dyqfblcq,ekwo,eyltua,hfwgo,mzrjis,qcbjxtt,qmlnbtrfv,rdbrpzcc,tmmmbrjfxt,xjzi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [294 chars] 'z'] != 'eatbvplj,fjwctulr,gkgxx,gmcvbnn,hwetl,jw[24 chars]pzwf' : Should be eatbvplj,fjwctulr,gkgxx,gmcvbnn,hwetl,jwyyacg,oykihdoj,rcgzak,rtpzwf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', 'a', 'b', 'b', 'b', [134 chars] 'z'] != 'bbwimxpg,gnfd,jbbaphjbbs,lvndv,zibcy' : Should be bbwimxpg,gnfd,jbbaphjbbs,lvndv,zibcy\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: [',', ',', ',', ',', ',', ',', ',', ',', [639 chars] 'z'] != 'aaqozfnzfn,bbtlbesij,ejouxcfet,eykviudvd[93 chars]jlck' : Should be aaqozfnzfn,bbtlbesij,ejouxcfet,eykviudvd,glnduo,ikycqwmmr,juicftc,mfhll,nlrpmtnln,oqexefwlbv,oysqe,pgrlfr,vezkuu,wnyy,yvbklmwiq,zldvhjlck\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.182s\n",
      "\n",
      "FAILED (failures=100)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_alpha(sort_alpha)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 12. Write a function to check if a given password is strong (at least 8 characters, at least one lower case, at least one upper case, at least one number and at least one special character). It should output True if strong and False if not.\n",
    "`Valid special characters: # @ ! $ % & ( ) ^ * [ ] { }`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def check_pass(string):\n",
    "    special_characters = [\"#\", \"@\", \"!\", \"$\", \"%\", \"&\", \"(\", \")\", \"^\", \"*\", \"[\", \"]\", \"{\", \"}\"]\n",
    "    if len(string) >= 8:\n",
    "        global condition_1\n",
    "        condition_1 = True\n",
    "    if any(c for c in string if c in special_characters):\n",
    "        global condition_2\n",
    "        condition_2 = True\n",
    "    if any(c for c in string if c.isdigit()):\n",
    "        global condition_3\n",
    "        condition_3 = True\n",
    "    if any(c for c in string if c.islower()):\n",
    "        global condition_4\n",
    "        condition_4 = True\n",
    "    if any(c for c in string if c.isupper()):\n",
    "        global condition_5\n",
    "        condition_5 = True     \n",
    "    if condition_1 == True and condition_2 == 0 and condition_3 == True and condition_4 == True and condition_5 == True:\n",
    "        return True\n",
    "    else:\n",
    "        return False"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "False"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "check_pass(\"Canicas99!\")\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 347,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      ".............E.E.E.E.E.E.E.E...EE...EE........EE.E.E.E.E.....E.E..E...E.E.EEE.............E....EE...\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_pass.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/Jaime/datamad1020-rev/module-1/lab-functions/mod/testing.py\", line 202, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "  File \"/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/unittest/case.py\", line 957, in assertAlmostEqual\n",
      "    if round(diff, places) == 0:\n",
      "TypeError: 'str' object cannot be interpreted as an integer\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.196s\n",
      "\n",
      "FAILED (errors=29)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_pass(check_pass)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
